github_checks:
  annotations: false

component_management:
  individual_components:
    - component_id: mcp_server_browser
      name: mcp-server-browser
      paths:
        - packages/aegnt-infra/mcp-servers/browser/src/**
    - component_id: ui_ae_action_parser
      name: ui-ae-action-parser
      paths:
        - packages/ui-ae/action-parser/src/**
    - component_id: ui_ae_sdk
      name: ui-ae-sdk
      paths:
        - packages/ui-ae/sdk/src/**
