packages:
  - 'apps/*'
  - 'apps/aegnt-27/src/*'
  - 'apps/ui-ae/src/*'
  - 'packages/ui-ae/**'
  - 'packages/aegnt-infra/**'
  - '!packages/aegnt-infra/create-new-mcp/template-*'
  - 'packages/common/*'
  - '!packages/ui-ae/visualizer'
